# Generated by Django 3.1 on 2020-08-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceFileUpload',
            fields=[
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_time', models.DateTimeField(auto_now_add=True)),
                ('invoiceid', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceStructuredData',
            fields=[
                ('invoiceid', models.CharField(blank=True, max_length=200, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_purchase', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchaser_name', models.CharField(blank=True, max_length=200, null=True)),
                ('purchaser_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('purchase_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('items_purchased', models.TextField(blank=True, null=True)),
                ('digitized', models.BooleanField(blank=True, default=False)),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
